name: tests
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ !contains(github.event.head_commit.message, 'FORCE_DEPLOY') }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Install dependencies
        run: make install

      - name: Test 
        run: make build && make test

